---
title: "Migration data analysis | Association Rules"
output: html_notebook
---

Import library

```{r}
library(arules)
```

Read Data

```{r}
data <- read.csv('MIGRACION_BDP.csv', sep=",")
head(data)
data
```

Delimitar columnas

```{r}
data2 <- data[, c(1, 2, 5, 9, 10, 11)]
```

Reglas fpgrowht

```{r}
reglas <- fim4r(data2, method = "fpgrowth", target = "rules", support = .1, confidence = .5)
```

Reglas por frame

```{r}
reglasframe <- as(reglas, "data.frame")
View(reglasframe)
```


REVISAR SOLO EDADES ENTRE 20 Y 28 (por analisis anteriores)

```{r}
dataEdades <- subset(data, PEI4 < 29 & PEI4 > 19)
dataEdades
```

```{r}
dataEdades2 <- dataEdades[, c(1, 2, 5, 9, 10, 11)]
reglas2 <- fim4r(dataEdades2, method = "fpgrowth", target = "rules", support = .15, confidence = .4)
reglasframe <- as(reglas2, "data.frame")
View(reglasframe)
```

Regla 24 y 42 Interesante

```{r}
primerRegla <- as(reglas2[c(24, 48)], "data.frame")
primerRegla
```

Regla 30 interesante. Norte y Oriente (DEP 13-22).

```{r}
segundaRegla <- as(reglas2[c(30)], "data.frame")
segundaRegla
```


SUBSET DE DEPARTAMENTOS DEL NORTE Y ORIENTE.

```{r}
dataDEP <- subset(data, DEPARTAMENTO >= 13)
dataDEP
dataDEP2 <- dataDEP[, c(2, 5, 9, 10, 11)]
reglas3 <- fim4r(dataDEP2, method = "fpgrowth", target = "rules", support = .15, confidence = .3)
reglasframe <- as(reglas3, "data.frame")
View(reglasframe)
```

Regla 28 y 76 muestra que la mayoría son de 19 en adelante.

```{r}
terceraRegla <- as(reglas3[c(20, 36)], "data.frame")
terceraRegla
```
